"""T-042 — projects, EDL versioning, and the media operations.

T-041 built an engine that no surface could reach. These tests are about the
thing that closes that: a project holds a versioned edit, and every media
capability is a registered operation, so the agent and the operator drive the
same code through the same authority and locking rules as everything else.

The append-only version model is the part worth pinning hardest. It is what
makes an agent's autonomous edit safe to accept — the previous version is always
recoverable — and what lets an operator ask "what did it change" and get an
answer from the data rather than from a summary written by the thing that
changed it.
"""

from __future__ import annotations

import json

import pytest

from promedia.core import db
from promedia.core.media import ffmpeg
from promedia.core.principal import agent, operator
from promedia.core.registry import Context, invoke, load_operations
from promedia.errors import MediaUnavailable, NotFound, ValidationError
from tests.conftest import declaration_original, make_config

OPERATIONS = load_operations()
needs_ffmpeg = pytest.mark.skipif(not ffmpeg.available(), reason="ffmpeg not installed")

MEDIA_OPS = {
    "create-project", "set-edl", "project", "list-projects",
    "project-versions", "render-project", "renders", "media-capabilities",
}


@pytest.fixture
def env(tmp_path, monkeypatch):
    monkeypatch.setenv("PROMEDIA_CREDENTIAL_STORE", str(tmp_path / "creds.json"))
    cfg = make_config(tmp_path)
    conn = db.connect(cfg.db_path)
    db.apply_schema(conn)
    yield cfg, Context(config=cfg, conn=conn, principal=agent("ag"), agent_id="agent-a")
    conn.close()


@pytest.fixture(scope="module")
def real_media(tmp_path_factory):
    """Genuine decodable media, generated by ffmpeg.

    conftest's media_file writes placeholder bytes, which is right for ingest
    and rights tests — they never decode it. A render does, so these tests need
    real frames. Synthetic rather than a checked-in fixture binary, so the suite
    carries no media of its own.
    """
    if not ffmpeg.available():
        pytest.skip("ffmpeg not installed")
    out = tmp_path_factory.mktemp("realmedia") / "src.mp4"
    ffmpeg.run([
        "-f", "lavfi", "-i", "testsrc=size=640x480:rate=25:duration=4",
        "-f", "lavfi", "-i", "sine=frequency=440:duration=4",
        "-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p",
        "-c:a", "aac", "-shortest", str(out),
    ], timeout_seconds=180)
    return out


@pytest.fixture
def source_asset(env, real_media):
    cfg, ctx = env
    return invoke(ctx, "ingest", {
        "source_path": str(real_media), "declaration": declaration_original(),
    })["asset_id"]


def an_edl(asset_id, **kw):
    base = {"aspect": "landscape_720",
            "clips": [{"asset_id": asset_id, "start": 0, "end": 1}]}
    base.update(kw)
    return base


# --- the version model -------------------------------------------------------


def test_a_new_project_starts_with_a_readable_empty_edit(env):
    """Version 1 exists immediately, so no caller ever handles 'no version yet'."""
    cfg, ctx = env
    created = invoke(ctx, "create-project", {"title": "  Launch teaser  "})
    assert created["edl_version"] == 1
    assert created["title"] == "Launch teaser", "title should be trimmed"

    current = invoke(ctx, "project", {"project_id": created["project_id"]})
    assert current["clips"] == 0 and current["edl_version"] == 1


def test_an_untitled_project_is_refused(env):
    cfg, ctx = env
    with pytest.raises(ValidationError):
        invoke(ctx, "create-project", {"title": "   "})


def test_editing_appends_a_version_and_the_previous_one_survives(env, source_asset):
    """AC-1, and the property that makes an agent's edit safe to accept."""
    cfg, ctx = env
    pid = invoke(ctx, "create-project", {"title": "P"})["project_id"]

    first = invoke(ctx, "set-edl", {"project_id": pid, "edl": an_edl(source_asset),
                                    "note": "first cut"})
    second = invoke(ctx, "set-edl", {
        "project_id": pid,
        "edl": an_edl(source_asset, aspect="vertical", text=[{"text": "Title"}]),
        "note": "went vertical",
    })

    assert (first["edl_version"], second["edl_version"]) == (2, 3)
    # The earlier edit is still there, unchanged.
    old = invoke(ctx, "project", {"project_id": pid, "version": 2})
    assert old["aspect"] == "landscape_720" and old["text_overlays"] == 0
    assert invoke(ctx, "project", {"project_id": pid})["aspect"] == "vertical"


def test_the_history_records_who_shaped_each_edit(env, source_asset):
    """'Did a human or an agent make this edit' is what an operator asks before
    approving what came out of it — the same reasoning that put authorship on
    rights declarations."""
    cfg, ctx = env
    pid = invoke(ctx, "create-project", {"title": "P"})["project_id"]
    invoke(ctx, "set-edl", {"project_id": pid, "edl": an_edl(source_asset)})

    op_ctx = Context(config=cfg, conn=ctx.conn, principal=operator("op"))
    invoke(op_ctx, "set-edl", {"project_id": pid, "edl": an_edl(source_asset),
                               "note": "operator tweak"})

    history = invoke(ctx, "project-versions", {"project_id": pid})["versions"]
    assert [v["version"] for v in history] == [3, 2, 1]
    assert history[0]["authored_kind"] == "operator"
    assert history[0]["note"] == "operator tweak"
    assert history[1]["authored_kind"] == "agent"


def test_an_invalid_edit_is_refused_and_not_stored(env, source_asset):
    """A stored version is one an operator may later restore. Storing an
    unrenderable one is a trap with a delay on it."""
    cfg, ctx = env
    pid = invoke(ctx, "create-project", {"title": "P"})["project_id"]
    bad = an_edl(source_asset)
    bad["clips"][0]["end"] = -5

    with pytest.raises(ValidationError):
        invoke(ctx, "set-edl", {"project_id": pid, "edl": bad})
    assert invoke(ctx, "project", {"project_id": pid})["edl_version"] == 1


def test_an_unknown_project_or_version_is_not_found(env):
    cfg, ctx = env
    with pytest.raises(NotFound):
        invoke(ctx, "project", {"project_id": "prj_nope"})
    pid = invoke(ctx, "create-project", {"title": "P"})["project_id"]
    with pytest.raises(NotFound):
        invoke(ctx, "project", {"project_id": pid, "version": 99})


# --- rendering ---------------------------------------------------------------


@needs_ffmpeg
def test_rendering_produces_a_file_and_records_where_it_came_from(env, source_asset):
    """A render that cannot be traced to the edit that produced it is the first
    thing anyone asks about an output they do not recognise."""
    cfg, ctx = env
    pid = invoke(ctx, "create-project", {"title": "P"})["project_id"]
    version = invoke(ctx, "set-edl", {"project_id": pid, "edl": an_edl(source_asset)})["edl_version"]

    result = invoke(ctx, "render-project", {"project_id": pid, "quality": "fast"})

    assert result["edl_version"] == version
    assert (result["width"], result["height"]) == (1280, 720)
    listed = invoke(ctx, "renders", {"project_id": pid})["renders"]
    assert len(listed) == 1
    assert listed[0]["output_exists"] is True
    assert listed[0]["edl_version"] == version


@needs_ffmpeg
def test_a_render_reports_what_it_did_not_do_as_asked(env, source_asset):
    """AC-4. Fabrication F-003: 'dissolve' renders a fade, and the render
    SUCCEEDS — which is exactly why it has to be reported. A silent
    substitution that succeeds prompts nobody to look."""
    cfg, ctx = env
    pid = invoke(ctx, "create-project", {"title": "P"})["project_id"]
    edl = an_edl(source_asset)
    edl["clips"].append({"asset_id": source_asset, "start": 1, "end": 2,
                         "transition_in": "dissolve"})
    invoke(ctx, "set-edl", {"project_id": pid, "edl": edl})

    result = invoke(ctx, "render-project", {"project_id": pid, "quality": "fast"})

    assert len(result["substitutions"]) == 1
    substitution = result["substitutions"][0]
    assert substitution["requested"] == "dissolve"
    assert substitution["fabrication"] == "F-003"
    # and it is persisted, not just returned once
    stored = invoke(ctx, "renders", {"project_id": pid})["renders"][0]
    assert stored["substitutions"][0]["requested"] == "dissolve"


@needs_ffmpeg
def test_a_render_with_no_substitutions_still_reports_the_field(env, source_asset):
    """A caller that has to ask whether a key exists will eventually stop asking."""
    cfg, ctx = env
    pid = invoke(ctx, "create-project", {"title": "P"})["project_id"]
    invoke(ctx, "set-edl", {"project_id": pid, "edl": an_edl(source_asset)})
    assert invoke(ctx, "render-project", {"project_id": pid, "quality": "fast"})["substitutions"] == []


def test_rendering_an_empty_edit_is_refused(env):
    cfg, ctx = env
    pid = invoke(ctx, "create-project", {"title": "P"})["project_id"]
    with pytest.raises(ValidationError) as excinfo:
        invoke(ctx, "render-project", {"project_id": pid})
    assert "no clips" in str(excinfo.value)


def test_rendering_an_edit_whose_media_is_gone_is_refused(env, source_asset):
    """The phantom-asset rule, applied to editing: a render must not silently
    produce a shorter video because one source vanished."""
    cfg, ctx = env
    pid = invoke(ctx, "create-project", {"title": "P"})["project_id"]
    invoke(ctx, "set-edl", {"project_id": pid, "edl": an_edl(source_asset)})
    ctx.conn.execute("UPDATE assets SET state = 'deleted', object_path = NULL WHERE id = ?",
                     (source_asset,))

    with pytest.raises(MediaUnavailable):
        invoke(ctx, "render-project", {"project_id": pid})


def test_rendering_an_edit_referencing_no_such_asset_is_refused(env, source_asset):
    cfg, ctx = env
    pid = invoke(ctx, "create-project", {"title": "P"})["project_id"]
    invoke(ctx, "set-edl", {"project_id": pid, "edl": an_edl("as_does_not_exist")})
    with pytest.raises(NotFound):
        invoke(ctx, "render-project", {"project_id": pid})


@needs_ffmpeg
def test_render_settings_come_from_configuration(env, source_asset):
    """Protocol 05. An operator on this hardware will want to trade quality
    against time, and a literal is one they cannot change."""
    cfg, ctx = env
    pid = invoke(ctx, "create-project", {"title": "P"})["project_id"]
    invoke(ctx, "set-edl", {"project_id": pid, "edl": an_edl(source_asset)})

    cfg.values["media"]["default_quality"] = "fast"
    assert invoke(ctx, "render-project", {"project_id": pid})["quality"] == "fast"
    # An explicit argument still wins over the configured default.
    assert invoke(ctx, "render-project",
                  {"project_id": pid, "quality": "balanced"})["quality"] == "balanced"


# --- locking, authority, and the registry ------------------------------------


@needs_ffmpeg
def test_a_second_agent_cannot_render_the_same_project_concurrently(env, source_asset, monkeypatch):
    """C-19. A render reads the edit and runs for minutes; without the lock, an
    edit changed mid-render yields an output attributed to a version it did not
    come from."""
    from promedia.core import projects as projects_layer
    from promedia.errors import EntityLocked

    cfg, ctx = env
    pid = invoke(ctx, "create-project", {"title": "P"})["project_id"]
    invoke(ctx, "set-edl", {"project_id": pid, "edl": an_edl(source_asset)})

    other = db.connect(cfg.db_path)
    beta = Context(config=cfg, conn=other, principal=agent("b"), agent_id="agent-b")
    seen = {}
    real = projects_layer._resolve_sources

    def probe(inner_ctx, document):
        if inner_ctx.agent_id == "agent-a":
            try:
                invoke(beta, "render-project", {"project_id": pid})
            except Exception as exc:  # noqa: BLE001 — which one is the point
                seen["error"] = exc
        return real(inner_ctx, document)

    monkeypatch.setattr(projects_layer, "_resolve_sources", probe)
    invoke(ctx, "render-project", {"project_id": pid, "quality": "fast"})
    other.close()

    assert isinstance(seen.get("error"), EntityLocked), f"got {seen.get('error')!r}"
    assert seen["error"].detail["entity_type"] == "project"
    assert seen["error"].detail["owner"] == "agent-a"


def test_every_media_operation_is_registered(env):
    """AC-2's precondition. Before T-042 the engine was on ZERO surfaces, which
    the parity gate cannot see — the mirror image of the F-1 defect it exists
    to catch."""
    assert MEDIA_OPS <= set(OPERATIONS)


def test_media_operations_are_agent_callable(env, source_asset):
    """F-2: producing a file is drafting, not publishing. Nothing here spends,
    publishes, or clears a rights flag."""
    for name in MEDIA_OPS:
        assert OPERATIONS[name].authority == "agent", f"{name} unexpectedly needs the operator"


def test_project_mutations_declare_their_entity_so_they_lock(env):
    """Locking is derived from the registry, not written per operation."""
    from promedia.core.registry import lock_target

    for name in ("create-project", "set-edl", "render-project"):
        assert OPERATIONS[name].mutates and OPERATIONS[name].entity == "project"
    # create-project has no project_id yet, so it takes no lock — nothing exists
    # for another agent to be holding.
    assert lock_target(OPERATIONS["create-project"], {}) is None
    assert lock_target(OPERATIONS["set-edl"], {"project_id": "p1"}) == ("project", "p1")
    assert lock_target(OPERATIONS["render-project"], {"project_id": "p1"}) == ("project", "p1")


def test_read_only_media_operations_take_no_lock(env):
    from promedia.core.registry import lock_target

    for name in ("project", "list-projects", "project-versions", "renders",
                 "media-capabilities"):
        assert lock_target(OPERATIONS[name], {"project_id": "p1"}) is None


def test_capabilities_reports_what_cannot_be_generated(env):
    """The requirement that a missing capability names what it needs rather
    than being discovered as a failure."""
    cfg, ctx = env
    caps = invoke(ctx, "media-capabilities", {})
    assert caps["ffmpeg_available"] is ffmpeg.available()
    assert {"dissolve", "fade", "cut"} <= set(caps["transitions"])
    missing = {item["capability"] for item in caps["not_available"]}
    assert "video generation" in missing
    for item in caps["not_available"]:
        assert item["needs"], f"{item['capability']} does not say what it needs"
    assert all(s["fabrication"] == "F-003" for s in caps["known_substitutions"])


def test_every_advertised_transition_is_either_implemented_or_reported(env):
    """The defect an independent audit found in F-003's first version.

    edl.validate() REJECTS a transition outside its vocabulary, so accepting one
    is an active promise that it is supported. Four of the seven emit no filter
    at all and render as hard cuts while reporting success — worse than the
    dissolve case, which at least produces a visible effect.

    Asserted as a rule over the whole vocabulary rather than a list of known-bad
    names, so a transition added to the EDL tomorrow is covered the day it is
    added. A hand-written list is exactly what drifted the first time.
    """
    from promedia.core.media.edl import TRANSITIONS
    from promedia.core.media.render import TRANSITION_REALITY

    assert set(TRANSITIONS) == set(TRANSITION_REALITY), (
        "a transition is advertised by the EDL but the renderer does not say "
        "what it really does — implement it, or record the substitution"
    )


@needs_ffmpeg
@pytest.mark.parametrize("transition", ["dissolve", "wipeleft", "wiperight",
                                        "slideup", "slidedown"])
def test_each_unimplemented_transition_is_reported_on_the_render(
    transition, env, source_asset
):
    """Not just dissolve. Every one that lies must say so, on the render that
    used it."""
    cfg, ctx = env
    pid = invoke(ctx, "create-project", {"title": "P"})["project_id"]
    edl = an_edl(source_asset)
    edl["clips"].append({"asset_id": source_asset, "start": 1, "end": 2,
                         "transition_in": transition})
    invoke(ctx, "set-edl", {"project_id": pid, "edl": edl})

    result = invoke(ctx, "render-project", {"project_id": pid, "quality": "fast"})
    reported = {s["requested"] for s in result["substitutions"]}
    assert transition in reported, f"'{transition}' rendered as something else, silently"


@needs_ffmpeg
def test_an_honest_transition_reports_nothing(env, source_asset):
    """The opposite direction: over-reporting would train people to ignore it."""
    cfg, ctx = env
    pid = invoke(ctx, "create-project", {"title": "P"})["project_id"]
    edl = an_edl(source_asset)
    edl["clips"].append({"asset_id": source_asset, "start": 1, "end": 2,
                         "transition_in": "fade"})
    invoke(ctx, "set-edl", {"project_id": pid, "edl": edl})
    assert invoke(ctx, "render-project",
                  {"project_id": pid, "quality": "fast"})["substitutions"] == []
